[2025-09-24T03:11:21.268+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl.extract scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T03:11:21.325+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl.extract scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T03:11:21.327+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-24T03:11:21.396+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract> on 2025-09-23 00:00:00+00:00
[2025-09-24T03:11:21.450+0000] {standard_task_runner.py:60} INFO - Started process 2673 to run task
[2025-09-24T03:11:21.479+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'extract', 'scheduled__2025-09-23T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_neotass.py', '--cfg-path', '/tmp/tmp4a4o14c3']
[2025-09-24T03:11:21.498+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask extract
[2025-09-24T03:11:21.724+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_etl.extract scheduled__2025-09-23T00:00:00+00:00 [running]> on host a5ae886b41c8
[2025-09-24T03:11:22.075+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_etl' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T00:00:00+00:00'
[2025-09-24T03:11:22.229+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_neotass.py", line 27, in extract
    data_oportunidades = pd.read_json('../../database/registros_oportunidades.json')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File ../../database/registros_oportunidades.json does not exist
[2025-09-24T03:11:22.275+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_etl, task_id=extract, execution_date=20250923T000000, start_date=20250924T031121, end_date=20250924T031122
[2025-09-24T03:11:22.369+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task extract (File ../../database/registros_oportunidades.json does not exist; 2673)
[2025-09-24T03:11:22.441+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-24T03:11:22.526+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-24T03:39:51.335+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl.extract scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T03:39:51.397+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl.extract scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T03:39:51.398+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-24T03:39:51.447+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract> on 2025-09-23 00:00:00+00:00
[2025-09-24T03:39:51.467+0000] {standard_task_runner.py:60} INFO - Started process 2810 to run task
[2025-09-24T03:39:51.478+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'extract', 'scheduled__2025-09-23T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_neotass.py', '--cfg-path', '/tmp/tmprzzqjj0h']
[2025-09-24T03:39:51.485+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask extract
[2025-09-24T03:39:51.746+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_etl.extract scheduled__2025-09-23T00:00:00+00:00 [running]> on host a573a6fc5665
[2025-09-24T03:39:52.132+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_etl' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T00:00:00+00:00'
[2025-09-24T03:39:52.294+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_neotass.py", line 27, in extract
    data_oportunidades = pd.read_json('opt/database/registros_oportunidades.json')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File opt/database/registros_oportunidades.json does not exist
[2025-09-24T03:39:52.329+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_etl, task_id=extract, execution_date=20250923T000000, start_date=20250924T033951, end_date=20250924T033952
[2025-09-24T03:39:52.366+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task extract (File opt/database/registros_oportunidades.json does not exist; 2810)
[2025-09-24T03:39:52.444+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-24T03:39:52.729+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-24T03:55:27.498+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl.extract scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T03:55:27.607+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl.extract scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T03:55:27.617+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-24T03:55:27.721+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract> on 2025-09-23 00:00:00+00:00
[2025-09-24T03:55:27.769+0000] {standard_task_runner.py:60} INFO - Started process 6213 to run task
[2025-09-24T03:55:27.824+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'extract', 'scheduled__2025-09-23T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_neotass.py', '--cfg-path', '/tmp/tmpgfw2l6jl']
[2025-09-24T03:55:27.870+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask extract
[2025-09-24T03:55:28.882+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_etl.extract scheduled__2025-09-23T00:00:00+00:00 [running]> on host c26bc00dd9a9
[2025-09-24T03:55:30.326+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_etl' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T00:00:00+00:00'
[2025-09-24T03:55:32.673+0000] {python.py:201} INFO - Done. Returned value was: (       Data de Registro  Quantidade  ...        Nome_Produto Valor_Unitario
0         1677283200000          23  ...         LiteTab Pro        2871.09
1         1712707200000          28  ...    QuantumPad Ultra        2854.77
2         1709078400000          35  ...       InfinityTab X        3550.90
3         1685836800000          25  ...       InfinityTab s         572.16
4         1729900800000          90  ...  Collaboration Edge        4685.77
...                 ...         ...  ...                 ...            ...
25258     1694217600000          25  ...            Sky Core         864.99
25259     1713052800000          46  ...            Galaxy S        2194.11
25260     1705708800000          93  ...        ScreenMate X        4643.23
25261     1716422400000          30  ...       InfinityTab X        3550.90
25262     1712448000000           1  ...      Velocity Ultra        3514.88

[25263 rows x 9 columns],       Data_Fatura  Quantidade  ...          Nome_Produto Valor_Unitario
0      2023-06-19          98  ...    Collaboration Edge        4685.77
1      2023-03-30          85  ...        Velocity Elite        1878.94
2      2024-02-18          97  ...  InfinityScreen Ultra        2639.11
3      2024-12-26           8  ...         PixelMaster S        4455.39
4      2023-06-26          34  ...           BizScreen S        4067.43
...           ...         ...  ...                   ...            ...
35582  2023-11-26          70  ...           CloudBook X        1579.75
35583  2024-12-17           6  ...         InfinityTab X        3550.90
35584  2023-05-24          27  ...    Collaboration Edge        4685.77
35585  2023-09-10          12  ...         PixelMaster S        4455.39
35586  2024-05-08          50  ...            AirTouch S        4123.59

[35587 rows x 9 columns])
[2025-09-24T03:55:34.602+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=extract, execution_date=20250923T000000, start_date=20250924T035527, end_date=20250924T035534
[2025-09-24T03:55:34.735+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-24T03:55:34.889+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
