[2025-09-24T16:40:22.135+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_neotass.transform scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T16:40:22.324+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_neotass.transform scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T16:40:22.325+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-24T16:40:22.438+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform> on 2025-09-23 00:00:00+00:00
[2025-09-24T16:40:22.495+0000] {standard_task_runner.py:60} INFO - Started process 3939 to run task
[2025-09-24T16:40:22.515+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_neotass', 'transform', 'scheduled__2025-09-23T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_neotass.py', '--cfg-path', '/tmp/tmpmfmpfrx9']
[2025-09-24T16:40:22.525+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask transform
[2025-09-24T16:40:22.907+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_etl_neotass.transform scheduled__2025-09-23T00:00:00+00:00 [running]> on host 0553782c08bf
[2025-09-24T16:40:23.964+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_etl_neotass' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T00:00:00+00:00'
[2025-09-24T16:40:29.300+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag_etl_neotass.py:80 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-09-24T16:40:29.302+0000] {logging_mixin.py:188} INFO - Directory already exists
[2025-09-24T16:40:34.395+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-24T16:40:34.515+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_etl_neotass, task_id=transform, execution_date=20250923T000000, start_date=20250924T164022, end_date=20250924T164034
[2025-09-24T16:40:34.644+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-24T16:40:34.963+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-24T17:34:33.754+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_neotass.transform scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T17:34:33.916+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_neotass.transform scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T17:34:33.917+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-24T17:34:34.139+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform> on 2025-09-23 00:00:00+00:00
[2025-09-24T17:34:34.170+0000] {standard_task_runner.py:60} INFO - Started process 4535 to run task
[2025-09-24T17:34:34.261+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_neotass', 'transform', 'scheduled__2025-09-23T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_neotass.py', '--cfg-path', '/tmp/tmp2ootse92']
[2025-09-24T17:34:34.330+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask transform
[2025-09-24T17:34:35.331+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_etl_neotass.transform scheduled__2025-09-23T00:00:00+00:00 [running]> on host dd5518020916
[2025-09-24T17:34:36.502+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_etl_neotass' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T00:00:00+00:00'
[2025-09-24T17:34:44.016+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag_etl_neotass.py:80 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-09-24T17:34:44.017+0000] {logging_mixin.py:188} INFO - Directory already exists
[2025-09-24T17:34:46.918+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-24T17:34:47.064+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_etl_neotass, task_id=transform, execution_date=20250923T000000, start_date=20250924T173433, end_date=20250924T173447
[2025-09-24T17:34:47.312+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-24T17:34:47.538+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-24T17:44:31.370+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_neotass.transform scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T17:44:31.687+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_neotass.transform scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T17:44:31.695+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-24T17:44:32.005+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform> on 2025-09-23 00:00:00+00:00
[2025-09-24T17:44:32.041+0000] {standard_task_runner.py:60} INFO - Started process 1113 to run task
[2025-09-24T17:44:32.116+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_neotass', 'transform', 'scheduled__2025-09-23T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_neotass.py', '--cfg-path', '/tmp/tmpduhwpobb']
[2025-09-24T17:44:32.130+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask transform
[2025-09-24T17:44:32.516+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_etl_neotass.transform scheduled__2025-09-23T00:00:00+00:00 [running]> on host ff9a178a756b
[2025-09-24T17:44:33.374+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_etl_neotass' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T00:00:00+00:00'
[2025-09-24T17:44:38.599+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag_etl_neotass.py:80 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-09-24T17:44:38.600+0000] {logging_mixin.py:188} INFO - Directory already exists
[2025-09-24T17:44:40.908+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-24T17:44:40.955+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_etl_neotass, task_id=transform, execution_date=20250923T000000, start_date=20250924T174431, end_date=20250924T174440
[2025-09-24T17:44:41.109+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-24T17:44:41.207+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-24T17:57:56.061+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_neotass.transform scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T17:57:56.142+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_neotass.transform scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T17:57:56.143+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-24T17:57:56.269+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform> on 2025-09-23 00:00:00+00:00
[2025-09-24T17:57:56.349+0000] {standard_task_runner.py:60} INFO - Started process 2894 to run task
[2025-09-24T17:57:56.424+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_neotass', 'transform', 'scheduled__2025-09-23T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_neotass.py', '--cfg-path', '/tmp/tmpue4v5rjn']
[2025-09-24T17:57:56.509+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask transform
[2025-09-24T17:57:57.268+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_etl_neotass.transform scheduled__2025-09-23T00:00:00+00:00 [running]> on host c88dd78f10f0
[2025-09-24T17:57:57.612+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_etl_neotass' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T00:00:00+00:00'
[2025-09-24T17:58:00.273+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag_etl_neotass.py:80 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-09-24T17:58:00.274+0000] {logging_mixin.py:188} INFO - Directory already exists
[2025-09-24T17:58:01.220+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-24T17:58:01.239+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_etl_neotass, task_id=transform, execution_date=20250923T000000, start_date=20250924T175756, end_date=20250924T175801
[2025-09-24T17:58:01.293+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-24T17:58:01.344+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
